-- MySQL Script generated by MySQL Workbench
-- dom 24 jan 2021 18:25:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GMArbitrage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GMArbitrage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GMArbitrage` ;
USE `GMArbitrage` ;

-- -----------------------------------------------------
-- Table `GMArbitrage`.`BTC_novadax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BTC_novadax` (
  `idBTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`ETH_novadax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`ETH_novadax` (
  `idETH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idETH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BCH_novadax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BCH_novadax` (
  `idBCH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBCH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`LTC_novadax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`LTC_novadax` (
  `idLTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`XRP_novadax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`XRP_novadax` (
  `idXRP` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idXRP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`EOS_novadax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`EOS_novadax` (
  `idEOS` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`DAI_novadax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`DAI_novadax` (
  `idDAI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDAI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BTC_bitcointrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BTC_bitcointrade` (
  `idBTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`XRP_bitcointrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`XRP_bitcointrade` (
  `idXRP` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idXRP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`EOS_bitcointrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`EOS_bitcointrade` (
  `idEOS` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`ETH_bitcointrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`ETH_bitcointrade` (
  `idETH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idETH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`DAI_bitcointrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`DAI_bitcointrade` (
  `idDAI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDAI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BCH_bitcointrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BCH_bitcointrade` (
  `idBCH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBCH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`LTC_bitcointrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`LTC_bitcointrade` (
  `idLTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BTC_binance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BTC_binance` (
  `idBTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`ETH_binance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`ETH_binance` (
  `idETH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idETH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`XRP_binance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`XRP_binance` (
  `idXRP` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idXRP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BTC_mercadobitcoin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BTC_mercadobitcoin` (
  `idBTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`ETH_mercadobitcoin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`ETH_mercadobitcoin` (
  `idETH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idETH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BCH_mercadobitcoin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BCH_mercadobitcoin` (
  `idBCH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBCH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`LTC_mercadobitcoin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`LTC_mercadobitcoin` (
  `idLTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`XRP_mercadobitcoin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`XRP_mercadobitcoin` (
  `idXRP` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idXRP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BTC_bitpreco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BTC_bitpreco` (
  `idBTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`ETH_bitpreco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`ETH_bitpreco` (
  `idETH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idETH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`BTC_bitcointoyou`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`BTC_bitcointoyou` (
  `idBTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBTC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`ETH_bitcointoyou`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`ETH_bitcointoyou` (
  `idETH` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idETH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GMArbitrage`.`LTC_bitcointoyou`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GMArbitrage`.`LTC_bitcointoyou` (
  `idLTC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bid` FLOAT UNSIGNED NOT NULL,
  `ask` FLOAT UNSIGNED NOT NULL,
  `volbid` FLOAT UNSIGNED NOT NULL,
  `volask` FLOAT UNSIGNED NOT NULL,
  `timestamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLTC`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
